### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by idio4** [BartvLaatum/GreenLight-Gym2#1]
Hello. I use ubuntu 24.04 so I installed CasADi by your guide. And the first question - why you firstly says to use "CasADi <= 3.5.5" and to use this ` sudo tar xzf casadi-linux-octave-6.1.0-v3.5.5.tar.gz -C /opt/casadi-3.5.5 --strip-components=1`  (because of this I installed the same version) but in the next step you use  another version... like this `sudo cp -r /opt/casadi-3.7.0-linux64-octave7.3.0/include/* /usr/local/include/
sudo cp    /opt/casadi-3.7.0-linux64-octave7.3.0/lib/libcasadi.so* /usr/local/lib/` I mean... why? You use higher version than 3.5.5... 
but okay I managed to install this CasADi and I tried to install `pip install -e .` and while building a wheel it gave me an error:

```
r(const char [16], const char [7], <brace-enclosed initializer list>, double, float&, casadi::Dict&)’
         59 |         integrator_func = integrator(
            |                           ~~~~~~~~~~^
         60 |             "integrator_func", "cvodes",
            |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         61 |             {{"x", x}, {"p", input_args_sym}, {"ode", dxdt}},
            |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         62 |             0., dt, opts
            |             ~~~~~~~~~~~~
         63 |         );
            |         ~
      In file included from /usr/local/include/casadi/core/core.hpp:50,
                       from /usr/local/include/casadi/casadi.hpp:29,
                       from gl_gym/environments/models/utils.hpp:5,
                       from gl_gym/environments/models/greenlight_model.cpp:6:
      /usr/local/include/casadi/core/integrator.hpp:82:26: note: candidate: ‘casadi::Function casadi::integrator(const std::string&, const std::string&, const SXDict&, const Dict&)’
         82 |   CASADI_EXPORT Function integrator(const std::string& name, const std::string& solver,
            |                          ^~~~~~~~~~
      /usr/local/include/casadi/core/integrator.hpp:82:26: note:   candidate expects 4 arguments, 6 provided
```
sorry if it seems messy but I think the most important part is  `candidate expects 4 arguments, 6 provided` , so it seems I did install casadi correctly, but the versions don't match. Am I right here? So what version of casadi I should use? (I will try now casadi-3.7.0-linux64-octave7.3.0 as you used in your example)

**Comment by idio4** [comment]
I tried casadi-3.7.0-linux64-octave7.3.0 .  Maybe I do something wrong but even with the same version there is no such folder at all as you used `sudo cp    /opt/casadi-3.7.0-linux64-octave7.3.0/lib/libcasadi.so* /usr/local/lib/,`  there is no lib even, only cmake, so I did it with cmake because it worked with 3.5.5 like that. 
And I tried again and got another error  _('The compiler can't determine whether to use the SXDict or MXDict' if it does matter)_  so I think I do something wrong completely, help me I really want to try your env

**Comment by BartvLaatum** [comment]
Hi there,

Sorry for the confusion. You indeed correctly installed casadi version 3.5.5. Discard version 3.7.0, which is a typo from my side. The error seems to be an issue with the inputs for the integrator function from a version higher than 3.5.5. I have pushed a newer version that should have fixed this. Additionally, rewrote the README.md file and rearranged some folders. 

Let me know if you manage to run the commands!

Best,
Bart

**Comment by idio4** [comment]
Thank you for your quick response and changes. I returned to the 3.5.5 version and tried again and yes the previous problem's been solved but now there is another one:
```
 gl_gym/environments/models/greenlight_model.cpp: In constructor ‘GreenLight::GreenLight(u_int8_t, u_int8_t, u_int8_t, u_int16_t, float)’:
      gl_gym/environments/models/greenlight_model.cpp:61:37: error: call of overloaded ‘integrator(const char [16], const char [7], <brace-enclosed initializer list>, casadi::Dict&)’ is ambiguous
         61 |         integrator_func = integrator(
            |                           ~~~~~~~~~~^
         62 |             "integrator_func", "cvodes",
            |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         63 |             {{"x", x}, {"p", input_args_sym}, {"ode", dxdt}},
            |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         64 |             opts
            |             ~~~~
         65 |         );
            |         ~
      In file included from /usr/local/include/casadi/core/core.hpp:50,
                       from /usr/local/include/casadi/casadi.hpp:29,
                       from gl_gym/environments/models/utils.hpp:5,
                       from gl_gym/environments/models/greenlight_model.cpp:6:
      /usr/local/include/casadi/core/integrator.hpp:82:26: note: candidate: ‘casadi::Function casadi::integrator(const std::string&, const std::string&, const SXDict&, const Dict&)’
         82 |   CASADI_EXPORT Function integrator(const std::string& name, const std::string& solver,
            |                          ^~~~~~~~~~
      /usr/local/include/casadi/core/integrator.hpp:84:26: note: candidate: ‘casadi::Function casadi::integrator(const std::string&, const std::string&, const MXDict&, const Dict&)’
         84 |   CASADI_EXPORT Function integrator(const std::string& name, const std::string& solver,
            |                          ^~~~~~~~~~
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
```

**Comment by idio4** [comment]
okay it was solved just like that:
```
integrator_func = integrator(
        "integrator_func", "cvodes",
        SXDict({{"x", x}, {"p", input_args_sym}, {"ode", dxdt}}),
        opts
    );
```

but here is another catch...  your  `sudo cp    /opt/casadi-3.5.5/lib/libcasadi.so* /usr/local/lib/` is not correct, because in this version this file `libcasadi.so` is inside of  casadi-3.5.5, so it should be  `sudo cp    /opt/casadi-3.5.5/libcasadi.so* /usr/local/lib/` I guess. And after that I had many problems with that it can't find my lib anyway... maybe that is what you meant by editing setup.py, but deepseek gave me this and everything finally works
```
ext_modules = [
    Pybind11Extension(
        "gl_gym.environments.models.greenlight_model",
        [module_path],
        include_dirs=include_dirs,
        libraries=["casadi"],
        library_dirs=[
            "/usr/local/lib",  # Primary search path
            "/opt/casadi-3.5.5",  # Direct path to CasADi
            os.environ.get("CASADI_LIB", ""),  # Allow override
        ],
        extra_compile_args=[
            "-std=c++17",
            "-O3"
        ],
        extra_link_args=[
            "-L/usr/local/lib",  # Explicit library path
            "-L/opt/casadi-3.5.5",  # Additional path
            f"-Wl,-rpath,/usr/local/lib:/opt/casadi-3.5.5",  # Runtime paths
        ],
    )
] 
```
